name: Build product
on:
  push:
    branches:
      - master
  workflow_dispatch: {}

env:
  VERSION_MAJOR: 1
  VERSION_MINOR: 0
  VERSION_REV_OFFSET: 10

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Make version
        id: version
        shell: bash
        run: |
          VERSION_REVISION=$(( ${{ github.run_number }} - $VERSION_REV_OFFSET ))
          echo "value=v${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_BUILD}.${VERSION_REVISION}" >> $GITHUB_OUTPUT
          echo "Version: ${VERSION_STRING}"
      - uses: actions/checkout@v5
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      # install net framework 4
      - name: Install Net4
        shell: pwsh
        run: |
          $downloadUrl = "https://download.microsoft.com/download/e/2/1/e21644b5-2df2-47c2-91bd-63c560427900/NDP452-KB2901907-x86-x64-AllOS-ENU.exe"
          $output = "NDP452-KB2901907-x86-x64-AllOS-ENU.exe"
          Invoke-WebRequest -Uri $downloadUrl -OutFile $output
          Start-Process -FilePath $output -ArgumentList "/quiet", "/norestart" -Wait
      # install msi from sdk/SharedFilesInstaller_File.msi
      # - name: Install SharedFilesInstaller
      #   run: |
      #     Start-Process msiexec.exe -ArgumentList '/i sdk/SharedFilesInstaller_File.msi /quiet /norestart' -Wait
      # build C# project from XNAContentCompiler.sln
      - name: Build XNAContentCompiler
        run: |
          msbuild XNAContentCompiler.sln /p:Configuration=Release /p:Platform=x86 /m
      # zip files in XNA-CC-CLI\bin\Release
      - name: Zip files
        run: |
          Compress-Archive -Path XNA-CC-CLI\bin\Release\* -DestinationPath XNAContentCompiler-${{ steps.version.outputs.value }}.zip
      # create release and contain zip file
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.value }}
          name: Release ${{ steps.version.outputs.value }}
          body: "Automated release from GitHub Actions"
          files: XNAContentCompiler-${{ steps.version.outputs.value }}.zip
          draft: false
          prerelease: false
          overwrite: true
          token: ${{ secrets.GITHUB_TOKEN }}

